[tcpout]
defaultGroup = splunkcloud

[tcpout:splunkcloud]
server = splunk-cloud-endpoint:9997
sslCertPath = $SPLUNK_HOME/etc/auth/server.pem
sslRootCAPath = $SPLUNK_HOME/etc/auth/cacert.pem
sslPassword = <redacted>
clientCert = $SPLUNK_HOME/etc/auth/server.pem

[tcpout-server://splunk-cloud-endpoint:9997]
